---
all:
  children:
    ghes_standalone:
      hosts:
        # Optional primary-only production appliance:
        # ghes-production:
        #   ansible_host: github.example.com

    ghes_primary:
      hosts:
        ghes-primary:
          ansible_host: github-primary.example.com

    ghes_replicas:
      hosts:
        ghes-replica:
          ansible_host: github-replica.example.com
        # ghes-replica-02:
        #   ansible_host: github-replica-02.example.com

    ghes:
      children:
        ghes_standalone:
        ghes_primary:
        ghes_replicas:
