---
all:
  children:
    ghes_standalone:
      hosts:
        ghes-staging:
          ansible_host: github-staging.example.com

    ghes_primary:
      hosts: {}

    ghes_replicas:
      hosts: {}

    ghes:
      children:
        ghes_standalone:
        ghes_primary:
        ghes_replicas:
